/controllers/positionController:
  ros__parameters:

    # PID controller for the angular velocity
    kp_angular: 15.0      # Proporcional gain 
    ki_angular: 5.0       # Integrative gain 
    kd_angular: 0.0       # Derivative gain 

    # PID controller for the linear velocity
    kp_linear: 1.0        # Proporcional gain 
    ki_linear: 0.0        # Integrative gain
    kd_linear: 0.0        # Derivative gain

    # Velocity limits 
    max_linear_vel: 1.8   # Max linear velocity in a straight line 
    min_linear_vel: 0.0   # Min linear speed for rotational movement
    
    # Debug / test condition 
    use_sim_time: false   # Use time from simulation
    debug: false          # Enable prints 
    unit_test: true      # Disable dependences from another nodes 
    frequency: 10         # Node frequency 